// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as bindings$0 from "../../../../guilhermt/myspec/internal/bindings/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "situation:open": bindings$0.SituationOpen;
            "situation:started": bindings$0.SituationStarted;
            "startup:changed": bindings$0.Startup;
            "state:changed": bindings$0.State;
            "transcript:changed": bindings$0.TranscriptEvent;
        }
    }
}
