/* =====================================================================
   ROUND 14 · the specimen of the components this round adds. Built from
   the same functions and classes as index.html, with the states forced by
   the classes the system uses (is-hover, is-focus, is-active, disabled,
   is-loading, is-error). Light and dark side by side. ?only=N shows one.
   ===================================================================== */
window.SPECIMEN = true;
const add = (h, c) => h.replace(/^\s*<(\w+) class="([^"]*)"/, (m, t, k) => `<${t} class="${k} ${c}"`);
const sni = (n, ic, extra = "", c = "", cur = false) => `<nav class="snav" aria-label="Settings"><a class="sni ${c}" href="#" ${cur ? 'aria-current="page"' : ""}>${I(ic)}<span class="grow">${n}</span>${extra}</a></nav>`;
const mrow = (n, chip, under = "", hint = "") => `<div class="mgrp"><div class="mrow"><span class="mn">${n}${hint ? `<span class="mhint">${hint}</span>` : ""}</span><span class="mc">${chip}</span>${under}</div></div>`;
const chip = (v, c = "", extra = "") => `<button class="chip sm ${c}" aria-haspopup="listbox" ${extra}>${v}${I("down")}</button>`;
const repo = (name, path, cnt, sub = "", c = "") => `<ul class="slist"><li class="srow rrow ${c}"><span class="si">${I("repo")}</span><div class="stx"><div class="s1"><span class="sn">${name}</span></div><div class="s2">${path}</div></div><span class="rc">${cnt}</span><span class="rm-w"><button class="btn ghost sm icon" aria-label="More for ${name}">${I("more")}</button></span>${sub}</li></ul>`;
const sub = (html, btn = "", c = "") => `<div class="srow-sub ${c}">${html}${btn}</div>`;
const board = (read, fail = "") => `<ul class="slist"><li class="srow"><span class="si">${I("board")}</span><div class="stx"><div class="s1"><span class="sn">Mobile App</span><a class="ghl" href="#">gmartins/projects/3${I("external")}</a></div><div class="s2">User · 2 repositories: android, ios</div><div class="s2">Final: Shipped · New cards: None</div></div><div class="sr-r">${read}<button class="btn sm">Edit…</button><button class="btn ghost sm">Remove…</button></div>${fail}</li></ul>`;
const lrow = (on, r, c, l, o = {}) => `<ul class="lrows"><li class="lrow ${o.off ? "is-off" : ""} ${o.cons ? "has-cons" : ""}"><label class="lr-l ${o.cls || ""}">${cbx(on, `${o.off ? "off-limits" : ""} ${o.cb || ""}`)}<span class="ln">${r}</span><span class="lc">${c}</span><span class="ll">${l}</span></label>${o.cons ? `<div class="lcons">${I("right")}${o.cons}</div>` : ""}</li></ul>`;
const scan = (on, r, p, o = {}) => `<ul class="lrows scanl"><li class="lrow ${o.off ? "is-off" : ""}"><label class="lr-l ${o.cls || ""}">${cbx(on, o.off ? "off-limits" : o.cb || "")}<span class="ln">${r}</span><span class="ll mono">${p}</span>${o.tag || ""}</label>${o.note ? `<div class="lcons">${o.note}</div>` : ""}</li></ul>`;
const hist = (i, c = "", narrow = false) => { const h = histRow(HIST[i], 0, false); return `<div class="lst hlst ${narrow ? "narrow" : ""}"><ul class="grpb" style="list-style:none;margin:0;padding:0">${c ? h.replace('class="cr hrow ', `class="cr hrow ${c} `) : h}</ul></div>`; };
const pstep = (n, d, edited, c = "") => `<ul class="slist plist2"><li><a class="srow prow ${c}" href="#"><span class="si">${I("prompt")}</span><span class="stx"><span class="s1"><span class="sn">${n}</span></span><span class="s2">${d}</span></span><span class="pst">${edited ? `<span class="dtag on">Edited ${edited}</span>` : `<span class="faint">Default</span>`}</span>${I("right", "i chev")}</a></li></ul>`;
const rbs = (c, on = false, dis = false) => `<span class="row"><label class="rbl"><span class="rb ${on ? "on" : ""} ${c}" aria-hidden="true"></span><span class="sr">Option</span></label><span class="faint">${dis ? "Can't choose" : on ? "Chosen" : "Not chosen"}</span></span>`;
const dlgStatic = (h) => h.replace('<div class="scrim" id="scrim">', '<div class="scrim static">');
const foot = (back, why, prim, err = false) => `<div class="dlg" role="group" aria-label="Footer"><div class="dlg-ft">${back ? `<button class="btn ghost bk">${I("left")}Back</button>` : ""}<span class="why ${err ? "err" : ""}">${why}</span><button class="btn ghost">Cancel</button>${prim}</div></div>`;

const COMPS = [
  { name: "Settings navigation", note: "Four pages at the left of Settings; the open one is the open place (veil and ring). Repositories carries the ◇ of a missing clone. ↑ ↓ move between pages. Below about 820 px of main area it lays out as a row above the page.",
    states: () => [["default", sni("Boards", "board")], ["hover", sni("Boards", "board", "", "is-hover")], ["focus", sni("Boards", "board", "", "is-focus")], ["active · pressed", sni("Boards", "board", "", "is-active")],
      ["open page", sni("Defaults", "sliders", "", "", true)], ["with a missing clone", sni("Repositories", "repo", `<span class="snx">${st("warn")}1</span>`)], ["open, with a missing clone", sni("Repositories", "repo", `<span class="snx">${st("warn")}1</span>`, "", true)]] },
  { name: "Default model row", note: "A stage and its chip. A choice changed from the factory is in ink 1, weight 500, with the factory in the tooltip; the factory choice is quiet. It saves at once.",
    states: () => [["factory", mrow("PR", chip("Opus 5.5 (1M) · medium"))], ["changed from the factory", mrow("PRD", chip("Opus 5.5 (1M) · xhigh", "own"))], ["with what else starts from it", mrow("PR review", chip("Fable 5.1 · high", "own"), "", "Also where a review of someone's pull request starts")],
      ["hover", mrow("Plan", chip("Opus 5.5 (1M) · medium", "own is-hover"))], ["focus", mrow("Plan", chip("Opus 5.5 (1M) · medium", "own is-focus"))], ["open", mrow("Plan", chip("Opus 5.5 (1M) · medium", "own", 'aria-expanded="true"'))],
      ["loading · saving", mrow("Plan", `<button class="chip sm own is-loading" aria-busy="true"><span class="spin"></span>Saving…</button>`)],
      ["error · couldn't save", mrow("Tech spec", chip("Opus 5.5 (1M) · xhigh", "own"), `<div class="mrow-err" role="alert">Couldn't save Opus 5.5 (1M) · high: no space left on the disk of ~/.local/share/myspec. Free some space, then try again. <button class="btn ghost xs">Try again</button></div>`)],
      ["unavailable", mrow("Step review", `<button class="chip sm own is-warn">${st("warn")}Opus 4.1 · high<span class="un">· unavailable</span>${I("down")}</button>`)],
      ["loading · reading the catalog", mrow("PRD", `<button class="chip sm own is-reading" aria-busy="true"><span class="rd">Opus 5.5 (1M) · xhigh</span>${I("down")}</button>`)]] },
  { name: "Model listbox", note: "Two groups: the model, then its effort. The factory choice is marked; a model without effort levels has none to choose. When no reading of the catalog worked, the list says why.",
    states: () => [["model and effort", modelList("Plan", "Opus 5.5 (1M) · medium", "Fable 5.1 · high")], ["the factory model chosen", modelList("PR review", "Opus 5.5 (1M) · high", "Opus 5.5 (1M) · high")],
      ["a model without effort", `<div class="pop menu mlist" role="menu" aria-label="Model of Commit"><div class="menu-cap">Model</div>${CATALOG.map((c) => `<button class="mi" role="menuitemradio" aria-checked="${c.m === "Haiku 4.5"}">${I("check", "i ck")}<span class="grow">${c.m}</span></button>`).join("")}<div class="menu-sep"></div><div class="menu-msg">Haiku 4.5 has no effort levels.</div></div>`],
      ["error · no reading of the catalog", modelList("PRD", "Opus 5.5 (1M) · xhigh", "Fable 5.1 · high", true)]] },
  { name: "Radio", note: "New in this round: a ring, the identity's dot when chosen. Used in the statuses of a board. The checkbox is round 11's.",
    states: () => [["default", rbs("")], ["hover", rbs("is-hover")], ["focus", rbs("is-focus")], ["checked", rbs("", true)], ["disabled", rbs("off-limits", false, true)], ["error", rbs("is-error")]] },
  { name: "Board row", note: "Title, the project on GitHub, the repositories, the statuses, the reading and the two actions. A failed reading is never red: a sunken line with ◇ and Try again, and the last reading stays in use.",
    states: () => [["read", board(`<span class="rs">Read 2m ago</span>`)], ["loading · reading", board(`<span class="rs is-reading"><span class="spin"></span>Reading…</span>`)], ["never read", board(`<span class="rs">Not read yet</span>`)],
      ["error · the reading failed", board(`<span class="rs is-failed">${st("warn")}Read failed 18m ago</span>`, sub(`${st("warn")}<span class="grow">GitHub's rate limit was reached. It resets at 14:32. The last reading stays in use.</span>`, `<button class="btn ghost xs">${I("refresh")}Try again</button>`))],
      ["trying again", board(`<span class="rs is-reading"><span class="spin"></span>Reading…</span>`, sub(`${st("warn")}<span class="grow">GitHub's rate limit was reached. It resets at 14:32. The last reading stays in use.</span>`, `<button class="btn ghost xs is-loading" aria-busy="true"><span class="spin"></span>Trying…</button>`))],
      ["actions · hover, focus", `<div class="row"><button class="btn sm is-hover">Edit…</button><button class="btn ghost sm is-focus">Remove…</button></div>`]] },
  { name: "Repository row", note: "Name, path, counts and ⋯ (Change path, Review instructions, Remove). The repositories that need a clone come first on the page. What blocks a task sits under the row, sunken, with its action: the same lines as Home.",
    states: () => [["cloned", repo("acme/api", `<span class="mono">~/code/api</span>`, "2 active · 14 archived · 3 reviews")], ["not cloned", repo("acme/billing", `<span class="faint">Not cloned</span>`, "No tasks or reviews", sub(`${st("warn")}<span class="grow">Its cards can't start a task until it's cloned.</span>`, `<button class="btn ghost xs">${I("clone")}Clone</button>`))],
      ["loading · cloning (with the clone folder chosen)", repo("acme/android", `<span class="faint">Not cloned</span>`, "No tasks or reviews", sub(`<span class="spin"></span><span class="grow">Cloning into ~/code/android…</span>`))],
      ["error · the clone failed", repo("acme/android", `<span class="faint">Not cloned</span>`, "No tasks or reviews", sub(`<span class="grow">gh: HTTP 403 · Resource not accessible by personal access token</span>`, `<button class="btn ghost xs">Try again</button>`, "err"))],
      ["clone missing", repo("acme/infra", `<span class="mono">~/code/infra</span>`, "1 active · 2 archived", sub(`${st("warn")}<span class="grow">The clone at <span class="mono">~/code/infra</span> is missing.</span>`, `<button class="btn ghost xs">Change path…</button>`))],
      ["error · Change path refused", repo("acme/infra", `<span class="mono">~/code/infra</span>`, "1 active · 2 archived", sub(`<span class="grow"><span class="mono">~/code/infra-old</span> is a clone of acme/terraform, not of acme/infra.</span>`, "", "err"))],
      ["menu open · Remove disabled", `<div class="pop menu rmenu" role="menu"><button class="mi" role="menuitem">Change path…</button><button class="mi is-hover" role="menuitem">Review instructions…<span class="sub">None</span></button><div class="menu-sep"></div><button class="mi danger" role="menuitem" aria-disabled="true">Remove…</button><div class="menu-msg">8 archived tasks and 4 reviews: delete them first.</div></div>`]] },
  { name: "Repository of a board, in its dialog", note: "Checked when the board manages it. How it gets linked at the right; an unchecked repository that the board managed says, on its row, where it goes.",
    states: () => [["registered, checked", lrow(true, "acme/api", "48 cards", "Registered · ~/code/api")], ["clone found", lrow(false, "acme/marketing-site", "2 cards", "Clone found · ~/code/marketing-site")], ["hover", lrow(false, "acme/marketing-site", "2 cards", "Clone found · ~/code/marketing-site", { cb: "is-hover", cls: "is-hover" })],
      ["focus", lrow(true, "acme/web", "31 cards", "Registered · ~/code/web", { cb: "is-focus" })], ["unchecked · it leaves the board", lrow(false, "acme/docs", "9 cards", "Registered · ~/code/docs", { cons: "Moves to No board: it has a clone and 3 archived tasks. Its tasks keep working." })],
      ["unchecked · it leaves MySpec", lrow(false, "acme/billing", "22 cards", "Registered · Not cloned", { cons: "Leaves MySpec: it has no clone, tasks or reviews." })], ["disabled · another board's", lrow(false, "acme/ios", "1 card", "acme/ios belongs to the board Mobile App.", { off: true })]] },
  { name: "Clone of the scan", note: "Add repository: the clones found in the home folder, the ones to register first; the registered ones folded at the end.",
    states: () => [["available", scan(false, "gmartins/dotfiles", "~/dotfiles")], ["checked", scan(true, "acme/marketing-site", "~/code/marketing-site")], ["links a clone", scan(true, "acme/billing", "~/src/billing", { note: "Registered without a clone: this links the clone to it." })],
      ["hover", scan(false, "gmartins/myspec", "~/pessoal/myspec", { cls: "is-hover", cb: "is-hover" })], ["focus", scan(false, "gmartins/myspec", "~/pessoal/myspec", { cb: "is-focus" })], ["disabled · registered", scan(false, "acme/api", "~/code/api", { off: true })],
      ["loading · adding", scan(true, "acme/marketing-site", "~/code/marketing-site", { cb: "is-loading" })],
      ["error · refused", scan(true, "acme/marketing-site", "~/code/marketing-site", { note: `<span class="err-t">acme/marketing-site is already registered at ~/src/marketing-site.</span>` })],
      ["scanning", `<div class="scan" role="status"><span class="spin"></span><span>Scanning your home folder…</span></div>`], ["nothing found", `<div class="scan"><span class="faint">No GitHub clones were found in your home folder, up to 6 folders deep.</span></div>`]] },
  { name: "Footer of a dialog in steps", note: "Back at the left from the second step on, what is missing or what the confirmation does beside the primary. The step is in the subtitle under the title.",
    states: () => [["step 1", foot(false, "", `<button class="btn primary">Continue <span class="k">Ctrl ↵</span></button>`)], ["step 3 · the consequence", foot(true, "acme/docs moves to No board.", `<button class="btn primary">Save <span class="k">Ctrl ↵</span></button>`)],
      ["hover · focus on Back", foot(true, "", `<button class="btn primary">Continue <span class="k">Ctrl ↵</span></button>`).replace('class="btn ghost bk"', 'class="btn ghost bk is-focus"')],
      ["loading · reading the project", foot(false, "Reading the board…", `<button class="btn primary is-loading" aria-busy="true"><span class="spin"></span>Reading…</button>`)],
      ["disabled · nothing to add", foot(false, "Check at least one repository.", `<button class="btn primary" disabled>Add board</button>`)],
      ["error · saving failed", foot(true, "Couldn't save the board: no space left on the disk of ~/.local/share/myspec.", `<button class="btn primary">Try again</button>`, true)]] },
  { name: "History row", note: "One list by date. The kind by its glyph, the name, where (card, pull request or board), the result and the hour. On a narrow list, where and the result go under the name.",
    states: () => [["task", hist(0)], ["One-Shot task", hist(3)], ["review · merged", hist(1)], ["review · closed", hist(39)], ["discussion", hist(2)], ["hover", hist(0, "is-hover")], ["focus", hist(0, "is-focus")], ["active · pressed", hist(0, "is-active")],
      ["just archived · arriving from its page", hist(0, "open")], ["narrow list", hist(5, "", true)],
      ["day header", `<h3 class="sech is-static"><span class="nm">Monday, Sep 22<span class="cnt">5</span></span></h3>`]] },
  { name: "Closing result", note: "One line per part: done with the check, skipped with a dash and its reason in ink 2, failed with the diamond and git's detail in mono. In History, on the page of the task that left, and in the toast's detail.",
    states: () => [["all done", closeResult([["done", "Worktree removed", ""], ["done", "Branch fix-the-flaky-login-e2e deleted", ""], ["done", "dev updated by 3 commits", ""]], "Sep 24 at 10:05")],
      ["a part skipped", closeResult(CLOSE_398, "Sep 24 at 15:02")], ["a part failed", closeResult([["done", "Worktree removed", ""], ["fail", "Branch audit-log couldn't be deleted", "error: Cannot delete branch 'audit-log' checked out at '/home/gm/code/api'"], ["skip", "dev was already up to date", ""]], "Sep 22 at 19:15")]] },
  { name: "Preview of a deletion", note: "What Delete task destroys, read from git when the dialog opens: the session that is interrupted, the worktree with its uncommitted files, the branch, what stays on GitHub. Deleting works even when the preview fails.",
    states: () => [["loading", `<ul class="dprev is-loading" role="status"><li class="skel"><i></i></li><li class="skel"><i></i></li></ul>`], ["read", (deleteTaskDialog().match(/<ul class="dprev"[\s\S]*?<\/ul>/) || [""])[0]],
      ["error · couldn't read the worktree", `<ul class="dprev"><li><span class="c">${st("warn")}</span><span class="w">Couldn't read the worktree<span class="d">git status failed: not a git repository. Deleting still removes it.</span></span></li></ul>`]] },
  { name: "Prompt row and placeholder", note: "The list of Prompts, a page of Settings (a revision of structure.md §4): the name, what the prompt opens, Default or Edited. A placeholder reads as a small mono tag, in the prompt and in the editor's column.",
    states: () => [["default", pstep("Tech spec", "Opens the tech spec session.", "")], ["edited", pstep("PRD", "Opens the PRD session of a task.", "Sep 20")], ["hover", pstep("Tech spec", "Opens the tech spec session.", "", "is-hover")], ["focus", pstep("Tech spec", "Opens the tech spec session.", "", "is-focus")], ["active · pressed", pstep("Tech spec", "Opens the tech spec session.", "", "is-active")],
      ["placeholder", `<span class="phc">{{prd_path}}</span>`]] },
  { name: "App notice and toast", note: "The notice says what failed and what to do, at the top of the main area, until dismissed; one at a time. The toast is for an item that left without being open, at the bottom left, for 10 seconds.",
    states: () => [["notice", `<div class="appnotice" role="alert"><span class="lbl">Couldn't delete web#2288 from History</span><span class="det">Permission denied on ~/.local/share/myspec/reviews/web-2288. Check the folder's owner, then try again.</span><button class="btn ghost sm">Dismiss</button></div>`],
      ["notice · Dismiss hover, focus", `<div class="appnotice" role="alert"><span class="lbl">Couldn't pause Rate limit per API key</span><span class="det">The session didn't answer in 10 seconds.</span><button class="btn ghost sm is-focus">Dismiss</button></div>`],
      ["toast · task", toast14("archive", "“Idempotency keys for payment intents” was archived", "Closed at 15:02 · dev not updated: another branch is checked out", `<button class="btn ghost xs">Open in History</button>`)],
      ["toast · review", toast14("merge", "web#2288 was merged, and its review ended", "Pass 2 was published at 13:10", `<button class="btn ghost xs">Open in History</button>`)],
      ["toast · discussion", toast14("archive", "“Usage alerts at 80% of the plan” was archived", "3 cards published", `<button class="btn ghost xs is-hover">Open in History</button>`)]] },
  { name: "Starting and the checks of this machine", note: "The steps of the start, named while they run, with the time of a slow one. The first run checks Claude Code and the GitHub CLI.",
    states: () => [["steps", `<ol class="bsteps"><li class="done"><span class="c">${I("check")}</span><span class="w">Opening your data</span><span class="d"></span></li><li class="run"><span class="c">${st("run")}</span><span class="w">Checking the clones of 12 repositories</span><span class="d">12s · ~/code/infra doesn't answer</span></li><li class="todo"><span class="c">${st("todo")}</span><span class="w">Reading the models of Claude Code</span><span class="d"></span></li></ol>`],
      ["checks", `<ul class="wchk"><li class="done"><span class="c">${I("check")}</span><span class="w">Claude Code 2.1.4</span></li><li class="warn"><span class="c">${st("warn")}</span><span class="w">GitHub CLI isn't signed in<span class="d">Run gh auth login in a terminal, then add a board.</span></span></li></ul>`]] },
];

document.addEventListener("DOMContentLoaded", () => {
  document.body.insertAdjacentHTML("afterbegin", SPRITE + SPRITE_14);
  document.addEventListener("click", (e) => e.stopPropagation(), true);
  document.addEventListener("keydown", (e) => e.stopPropagation(), true);
  const side = (mode, sts) => `<div class="side" data-theme="${mode}"><div class="mode">${mode}</div>${sts.map(([l, h]) => `<div class="stt"><span class="l">${l}</span><div class="v">${h}</div></div>`).join("")}</div>`;
  const body = COMPS.filter((c, k) => !Q.has("only") || String(k) === Q.get("only")).map((c) => { const sts = c.states(); return `<section class="comp"><h2>${c.name}</h2><p>${c.note}</p><div class="pairs">${side("light", sts)}${side("dark", sts)}</div></section>`; }).join("");
  document.body.insertAdjacentHTML("beforeend", `<main class="spc"><header><h1>The rest · components</h1><p>Each component this round adds, in every state, light and dark side by side.</p></header>${body}</main><pre id="report" class="report" hidden></pre>`);
  if (Q.has("audit")) setTimeout(() => { const pre = document.getElementById("report"); pre.hidden = false; const unnamed = [...document.querySelectorAll("button, a[href]")].filter((b) => b.offsetParent && !(b.getAttribute("aria-label") || b.textContent.trim())).length; pre.textContent = JSON.stringify({ contrastBelow45: contrastAudit(), unnamedControls: unnamed }, null, 1); }, 1200);
});
