// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AttentionService is what the frontend tells the app about the situations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ViewSituation says the place of a situation is on screen with the window in
 * front: a notification about it is out of date and goes away.
 */
export function ViewSituation(id: string): $CancellablePromise<void> {
    return $Call.ByID(3253195996, id);
}
