// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoardService is the board API the frontend calls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddBoard registers the board at url with what the user chose, then reads it.
 */
export function AddBoard(url: string, req: $models.SaveBoardRequest): $CancellablePromise<void> {
    return $Call.ByID(4074067882, url, req);
}

/**
 * AddRepositoryToBoard ties one more repository to a board.
 */
export function AddRepositoryToBoard(boardID: string, choice: $models.BoardRepositoryChoice): $CancellablePromise<void> {
    return $Call.ByID(1548079021, boardID, choice);
}

/**
 * CardContext is the context a task created from a card starts with, without
 * the text the user adds.
 */
export function CardContext(boardID: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(823451088, boardID, key);
}

/**
 * CheckBoardRepository checks a repository the user typed as owner/name for the
 * board of boardID, "" for a board not registered yet.
 */
export function CheckBoardRepository(boardID: string, fullName: string): $CancellablePromise<$models.BoardRepositoryOption> {
    return $Call.ByID(2152955379, boardID, fullName);
}

/**
 * PreviewBoard reads the board at url for registering it: its statuses, with
 * the final ones pre-marked, and the repositories its issues are in.
 */
export function PreviewBoard(url: string): $CancellablePromise<$models.BoardPreview> {
    return $Call.ByID(858145895, url);
}

/**
 * PreviewEditBoard reads a registered board again for editing it.
 */
export function PreviewEditBoard(id: string): $CancellablePromise<$models.BoardPreview> {
    return $Call.ByID(2669015011, id);
}

/**
 * PreviewRemoveBoard is what removing a board does to its repositories.
 */
export function PreviewRemoveBoard(id: string): $CancellablePromise<$models.BoardRemoval> {
    return $Call.ByID(894141847, id);
}

/**
 * RefreshBoard starts a reading of a board. It returns at once; the reading
 * arrives as state.
 */
export function RefreshBoard(id: string): $CancellablePromise<void> {
    return $Call.ByID(4073962706, id);
}

/**
 * RefreshCard reads one card of a board again.
 */
export function RefreshCard(boardID: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(2592889960, boardID, key);
}

/**
 * RemoveBoard removes a board and releases every repository of it.
 */
export function RemoveBoard(id: string): $CancellablePromise<void> {
    return $Call.ByID(406911849, id);
}

/**
 * UpdateBoard saves what the user chose for a registered board.
 */
export function UpdateBoard(id: string, req: $models.SaveBoardRequest): $CancellablePromise<void> {
    return $Call.ByID(2521260950, id, req);
}
