// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiscussionService is the discussion API the frontend calls. The conversation
 * of a discussion goes through TaskService, like the one of a task: the id of
 * the discussion is the id of the item behind it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddDraftDependency records that a card can only start after another one.
 */
export function AddDraftDependency(id: string, draftID: string, ref: string): $CancellablePromise<void> {
    return $Call.ByID(2682893104, id, draftID, ref);
}

/**
 * ArchiveDiscussion takes a discussion out of the list and into the history,
 * with its conversation kept for the user to read.
 */
export function ArchiveDiscussion(id: string): $CancellablePromise<void> {
    return $Call.ByID(951431411, id);
}

/**
 * DecideDraft records what the user decided about one draft: "", approved or
 * discarded.
 */
export function DecideDraft(id: string, draftID: string, decision: string): $CancellablePromise<void> {
    return $Call.ByID(2607286370, id, draftID, decision);
}

/**
 * DeleteDiscussion removes a discussion for good, active or in the history.
 * What it already published on GitHub stays there.
 */
export function DeleteDiscussion(id: string): $CancellablePromise<void> {
    return $Call.ByID(381600316, id);
}

/**
 * DiscussionContext is the context a discussion would start with, built from
 * the stored reading of the board. It creates nothing: the dialog shows it
 * while the user is still choosing what to discuss.
 */
export function DiscussionContext(req: $models.DiscussionContextRequest): $CancellablePromise<string> {
    return $Call.ByID(512760810, req);
}

/**
 * GroupIntoEpic creates an epic over the given cards and points every one of
 * them at it. It answers with the id of the epic.
 */
export function GroupIntoEpic(id: string, draftIDs: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(1067082565, id, draftIDs);
}

/**
 * PublishEpic asks for an epic and the cards under it to go to GitHub
 * together. It returns as soon as the publication is asked for; what it writes
 * arrives as state.
 */
export function PublishEpic(id: string, draftID: string): $CancellablePromise<void> {
    return $Call.ByID(3576975, id, draftID);
}

/**
 * ReadDiscussionArtifact returns the content of an artifact of a discussion by
 * file name: context.md, discussion.md or drafts.md.
 */
export function ReadDiscussionArtifact(id: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3201103609, id, name);
}

/**
 * RemoveDraftDependency drops a dependency of a card.
 */
export function RemoveDraftDependency(id: string, draftID: string, ref: string): $CancellablePromise<void> {
    return $Call.ByID(2139859291, id, draftID, ref);
}

/**
 * RetryPublish sends a draft whose publication failed to GitHub again, from
 * the step it stopped at.
 */
export function RetryPublish(id: string, draftID: string): $CancellablePromise<void> {
    return $Call.ByID(4258914070, id, draftID);
}

/**
 * SetDraftEpic records the epic of a card: an epic draft of the discussion, an
 * issue as owner/name#number, or "" for none.
 */
export function SetDraftEpic(id: string, draftID: string, ref: string): $CancellablePromise<void> {
    return $Call.ByID(2144905169, id, draftID, ref);
}

/**
 * SetDraftModule records the module of a card; "" is a card with none.
 */
export function SetDraftModule(id: string, draftID: string, $module: string): $CancellablePromise<void> {
    return $Call.ByID(3422697428, id, draftID, $module);
}

/**
 * SetDraftRepository records the registered repository a new card or an epic
 * is created in.
 */
export function SetDraftRepository(id: string, draftID: string, repositoryID: string): $CancellablePromise<void> {
    return $Call.ByID(3896501600, id, draftID, repositoryID);
}

/**
 * SetDraftText records the title and the body the user left on a draft, which
 * is what a publication sends.
 */
export function SetDraftText(id: string, draftID: string, title: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(2970110587, id, draftID, title, body);
}

/**
 * StartDiscussion opens a discussion of a demand of a board: it creates the
 * discussion with its artifact folder and its conversation, and answers with
 * the id of the discussion.
 */
export function StartDiscussion(req: $models.StartDiscussionRequest): $CancellablePromise<string> {
    return $Call.ByID(245635825, req);
}
