// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService pages the History beyond the window the state carries,
 * searches the whole of it and finds an archived item by id.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetArchived is the archived item with the id, in whichever kind it is; every
 * field is nil when no archived item has it.
 */
export function GetArchived(id: string): $CancellablePromise<$models.ArchivedItem> {
    return $Call.ByID(2096556791, id);
}

/**
 * ListArchived is the page of the History after the cursor that matches the
 * query and the repository, with how many items of the whole History match.
 */
export function ListArchived(request: $models.HistoryRequest): $CancellablePromise<$models.HistoryPage> {
    return $Call.ByID(4233117585, request);
}
