// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Notice is a path the app refused to open.
 */
export interface Notice {
    "path": string;

    /**
     * Reason is not_found, not_directory, not_readable or last_recent_missing.
     * It stays a string so the generated bindings leave the narrowing to the
     * frontend union types instead of emitting a TypeScript enum.
     */
    "reason": string;
}

/**
 * Recent is a workspace the user opened before.
 */
export interface Recent {
    "name": string;
    "path": string;
}

/**
 * Repo is a git repository inside the open workspace.
 */
export interface Repo {
    "name": string;
    "path": string;
}

/**
 * State is everything the interface renders, produced by Go and never derived
 * on the frontend.
 */
export interface State {
    /**
     * nil on the welcome screen
     */
    "workspace": Workspace | null;

    /**
     * never nil
     */
    "recents": Recent[] | null;

    /**
     * Theme is system, light or dark, a string for the same reason as
     * Notice.Reason.
     */
    "theme": string;
    "systemDark": boolean;
    "notice": Notice | null;
}

/**
 * Workspace is the open folder and the repositories found in it.
 */
export interface Workspace {
    "name": string;
    "path": string;
    "repos": Repo[] | null;
}
