// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionEntry is a tool call the agent made.
 */
export interface ActionEntry {
    "toolUseId": string;
    "tool": string;
    "label": string;
    "target": string;

    /**
     * Status is running, done, error or interrupted.
     */
    "status": string;
}

/**
 * AssistantEntry is one content block of an assistant message.
 */
export interface AssistantEntry {
    "messageId": string;
    "blockIndex": number;
    "text": string;
    "complete": boolean;
    "interrupted": boolean;
}

/**
 * CreateTaskRequest is the task the user filled in the creation dialog.
 */
export interface CreateTaskRequest {
    "name": string;

    /**
     * "" for root
     */
    "repoPath": string;
    "initialContext": string;
}

/**
 * Entry is one item of a conversation. Exactly one payload is set, the one
 * matching Kind.
 */
export interface Entry {
    "id": string;
    "seq": number;

    /**
     * TurnID is the id of the user entry that started the turn of this entry.
     */
    "turnId": string;

    /**
     * Kind is user, assistant, action, permission, question, marker or error.
     */
    "kind": string;
    "createdAt": string;
    "user": UserEntry | null;
    "assistant": AssistantEntry | null;
    "action": ActionEntry | null;
    "permission": PermissionEntry | null;
    "question": QuestionEntry | null;
    "marker": MarkerEntry | null;
    "error": ErrorEntry | null;
}

/**
 * ErrorEntry is a failure shown in the conversation.
 */
export interface ErrorEntry {
    /**
     * Kind is process_exit, start_failed, not_found, not_logged_in or
     * turn_error.
     */
    "kind": string;
    "message": string;
    "retryable": boolean;
}

/**
 * MarkerEntry is a milestone of the conversation.
 */
export interface MarkerEntry {
    /**
     * Type is prd_written, prd_updated, tech_spec_written, tech_spec_updated,
     * plan_written, plan_updated, stage_started, step_started, compacted or
     * interrupted.
     */
    "type": string;
    "preTokens": number;

    /**
     * Stage belongs to stage_started alone and Step to step_started alone;
     * Restarted belongs to both.
     */
    "stage": string;
    "step": number;
    "restarted": boolean;
}

/**
 * Notice is a path the app refused to open.
 */
export interface Notice {
    "path": string;

    /**
     * Reason is not_found, not_directory, not_readable or last_recent_missing.
     * It stays a string so the generated bindings leave the narrowing to the
     * frontend union types instead of emitting a TypeScript enum.
     */
    "reason": string;
}

/**
 * PermissionEntry is a tool the agent asked to use. Input and Suggestions carry
 * raw JSON as a string, because the bindings generator has no stable type for
 * json.RawMessage; the frontend parses them.
 */
export interface PermissionEntry {
    "requestId": string;
    "toolUseId": string;
    "tool": string;
    "displayName": string;
    "description": string;

    /**
     * JSON object
     */
    "input": string;

    /**
     * JSON array, "" when absent
     */
    "suggestions": string;
    "blockedPath": string;
    "decisionReason": string;
    "suppressAlwaysAllow": boolean;
    "defaultToNo": boolean;

    /**
     * Status is pending, allowed, allowed_session, denied or cancelled.
     */
    "status": string;
    "denyMessage": string;

    /**
     * "" while pending
     */
    "answeredAt": string;
}

/**
 * PlanProblem is one reason the step files are not a valid plan.
 */
export interface PlanProblem {
    /**
     * "" for the plan as a whole
     */
    "file": string;
    "message": string;
}

/**
 * Question is one of the questions of an AskUserQuestion call.
 */
export interface Question {
    "question": string;
    "header": string;

    /**
     * never nil
     */
    "options": QuestionOption[] | null;
    "multiSelect": boolean;
}

/**
 * QuestionEntry is a structured question the agent asked.
 */
export interface QuestionEntry {
    "requestId": string;
    "toolUseId": string;

    /**
     * never nil
     */
    "questions": Question[] | null;

    /**
     * question text -> label(s); nil while pending
     */
    "answers": { [_ in string]?: string } | null;

    /**
     * Status is pending, allowed or cancelled.
     */
    "status": string;
}

/**
 * QuestionOption is one answer offered for a question.
 */
export interface QuestionOption {
    "label": string;
    "description": string;
}

/**
 * Recent is a workspace the user opened before.
 */
export interface Recent {
    "name": string;
    "path": string;
}

/**
 * Repo is a git repository inside the open workspace.
 */
export interface Repo {
    "name": string;
    "path": string;
}

/**
 * State is everything the interface renders, produced by Go and never derived
 * on the frontend.
 */
export interface State {
    /**
     * nil on the welcome screen
     */
    "workspace": Workspace | null;

    /**
     * never nil
     */
    "recents": Recent[] | null;

    /**
     * Theme is system, light or dark, a string for the same reason as
     * Notice.Reason.
     */
    "theme": string;
    "systemDark": boolean;
    "notice": Notice | null;

    /**
     * tasks of the open workspace; never nil
     */
    "tasks": TaskSummary[] | null;
}

/**
 * Step is one step of the plan of a task.
 */
export interface Step {
    "number": number;

    /**
     * name inside steps/, the artifact is "steps/" + File
     */
    "file": string;
    "title": string;

    /**
     * Repository is the value the file carries; RepoPath is "" when no
     * repository of the task matches it.
     */
    "repository": string;
    "repoPath": string;

    /**
     * Status is not_started, preparing, blocked, implementing or
     * awaiting_review, a string for the same reason as Notice.Reason.
     */
    "status": string;

    /**
     * Phase is fetching, creating or checking while preparing; "" otherwise.
     */
    "phase": string;

    /**
     * blocked only
     */
    "block": StepBlock | null;

    /**
     * "" until the worktree exists
     */
    "worktreePath": string;
}

/**
 * StepBlock is why a step is blocked.
 */
export interface StepBlock {
    /**
     * Reason is dirty_worktree, fetch_failed, no_base_branch, path_exists,
     * branch_exists, git_failed or no_repository, a string for the same reason
     * as Notice.Reason.
     */
    "reason": string;

    /**
     * what git said, or the status lines of a dirty worktree
     */
    "detail": string;

    /**
     * dirty worktree only
     */
    "files": number;
}

/**
 * TaskSummary is a task of the open workspace with the state of its session.
 */
export interface TaskSummary {
    "id": string;
    "name": string;

    /**
     * "" for a root task
     */
    "repoPath": string;
    "dir": string;

    /**
     * Stage is prd, tech_spec, plan or implementation, a string for the same
     * reason as Notice.Reason.
     */
    "stage": string;

    /**
     * Revisiting is a stage reopened by the user, which moves on only when
     * they say so.
     */
    "revisiting": boolean;

    /**
     * SessionStatus is working, waiting, needs_permission, paused or error.
     */
    "sessionStatus": string;
    "turnRunning": boolean;
    "processRunning": boolean;
    "retryAttempt": number;
    "contextPercent": number;
    "pendingCount": number;
    "corrections": number;
    "hasPrd": boolean;
    "hasTechSpec": boolean;

    /**
     * never nil
     */
    "steps": Step[] | null;

    /**
     * the step that runs or runs next; 0 when the task has no steps
     */
    "currentStep": number;

    /**
     * never nil
     */
    "planProblems": PlanProblem[] | null;
    "canContinue": boolean;
    "artifactVersion": number;
    "lastError": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Transcript is the whole conversation of a task.
 */
export interface Transcript {
    "taskId": string;
    "sessionId": string;

    /**
     * Stage is the stage of the session the conversation belongs to.
     */
    "stage": string;

    /**
     * never nil
     */
    "entries": Entry[] | null;

    /**
     * never nil
     */
    "pending": Entry[] | null;
}

/**
 * TranscriptEvent is one change to the conversation of a task.
 */
export interface TranscriptEvent {
    "taskId": string;

    /**
     * Kind is entry, text, remove or reset.
     */
    "kind": string;
    "entry": Entry | null;
    "entryId": string;
    "text": string;
}

/**
 * UserEntry is a message sent to the agent: one the user wrote, or one the app
 * sent on their behalf.
 */
export interface UserEntry {
    "text": string;
    "pending": boolean;
    "prompt": boolean;
    "app": boolean;
}

/**
 * Workspace is the open folder and the repositories found in it.
 */
export interface Workspace {
    "name": string;
    "path": string;
    "repos": Repo[] | null;
}
