// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionEntry is a tool call the agent made.
 */
export interface ActionEntry {
    "toolUseId": string;
    "tool": string;
    "label": string;
    "target": string;

    /**
     * Status is running, done, error or interrupted.
     */
    "status": string;
}

/**
 * ArchivedPR is the pull request an archived task opened.
 */
export interface ArchivedPR {
    "number": number;
    "url": string;
    "state": string;
}

/**
 * ArchivedStep is one step of an archived task, as the plan wrote it.
 */
export interface ArchivedStep {
    "number": number;

    /**
     * name inside steps/, the artifact is "steps/" + File; one-shot.md for the single step of a One-Shot task
     */
    "file": string;
    "title": string;

    /**
     * never nil
     */
    "reports": StepReport[] | null;
}

/**
 * ArchivedTask is a finished task, as the history shows it: its artifacts and
 * what it touched, and nothing that runs.
 */
export interface ArchivedTask {
    "id": string;
    "name": string;
    "repositoryId": string;

    /**
     * owner/name
     */
    "repository": string;

    /**
     * Mode is structured or one_shot, a string for the same reason as
     * State.Theme.
     */
    "mode": string;
    "hasPrd": boolean;
    "hasTechSpec": boolean;
    "hasOneShot": boolean;

    /**
     * never nil
     */
    "steps": ArchivedStep[] | null;

    /**
     * nil when the task opened none
     */
    "pr": ArchivedPR | null;
    "artifactVersion": number;
    "createdAt": string;
    "archivedAt": string;
}

/**
 * AssistantEntry is one content block of an assistant message.
 */
export interface AssistantEntry {
    "messageId": string;
    "blockIndex": number;
    "text": string;
    "complete": boolean;
    "interrupted": boolean;
}

/**
 * BranchPreview is the branch the deletion of a task would delete, and whether
 * its commits are safe elsewhere.
 */
export interface BranchPreview {
    "name": string;
    "merged": boolean;
    "error": string;
}

/**
 * CloseResult is what closing a task did.
 */
export interface CloseResult {
    "worktree": CloseStep;
    "branch": CloseStep;
    "base": CloseStep;
    "worktreePath": string;
    "branchName": string;
    "baseBranch": string;
    "baseCommits": number;
    "closedAt": string;
}

/**
 * CloseStep is one part of the closing of a task.
 */
export interface CloseStep {
    /**
     * Outcome is done, skipped or failed, a string for the same reason as
     * State.Theme.
     */
    "outcome": string;

    /**
     * Reason is missing, not_merged, not_checked_out, dirty, no_upstream,
     * diverged or up_to_date; skipped only.
     */
    "reason": string;
    "detail": string;
}

/**
 * CreateTaskRequest is the task the user filled in the creation dialog.
 */
export interface CreateTaskRequest {
    "name": string;
    "repositoryId": string;
    "initialContext": string;

    /**
     * structured or one_shot; "" is structured
     */
    "mode": string;

    /**
     * Models are the choices of the creation dialog. A stage left out takes the
     * default of the app.
     */
    "models": StageModel[] | null;

    /**
     * manual or agent; "" takes the default of the app
     */
    "reviewMode": string;
}

/**
 * DeletePreview is what deleting a task would destroy, as the confirmation
 * dialog spells it out.
 */
export interface DeletePreview {
    "sessionRunning": boolean;

    /**
     * nil when there is none
     */
    "worktree": WorktreePreview | null;

    /**
     * nil when there is none
     */
    "branch": BranchPreview | null;

    /**
     * nil when there is none
     */
    "pr": PRPreview | null;
}

/**
 * DeleteResult is what deleting a task left behind.
 */
export interface DeleteResult {
    /**
     * nil when git removed everything
     */
    "leftover": Leftover | null;
}

/**
 * Entry is one item of a conversation. Exactly one payload is set, the one
 * matching Kind.
 */
export interface Entry {
    "id": string;
    "seq": number;

    /**
     * TurnID is the id of the user entry that started the turn of this entry.
     */
    "turnId": string;

    /**
     * Kind is user, assistant, action, permission, question, marker or error.
     */
    "kind": string;
    "createdAt": string;
    "user": UserEntry | null;
    "assistant": AssistantEntry | null;
    "action": ActionEntry | null;
    "permission": PermissionEntry | null;
    "question": QuestionEntry | null;
    "marker": MarkerEntry | null;
    "error": ErrorEntry | null;
}

/**
 * ErrorEntry is a failure shown in the conversation.
 */
export interface ErrorEntry {
    /**
     * Kind is process_exit, start_failed, not_found, not_logged_in or
     * turn_error.
     */
    "kind": string;
    "message": string;
    "retryable": boolean;
}

/**
 * Leftover is what git could not remove when a task was deleted.
 */
export interface Leftover {
    /**
     * "" when the folder went
     */
    "path": string;

    /**
     * "" when the branch went
     */
    "branch": string;
    "error": string;
}

/**
 * MarkerEntry is a milestone of the conversation.
 */
export interface MarkerEntry {
    /**
     * Type is prd_written, prd_updated, tech_spec_written, tech_spec_updated,
     * plan_written, plan_updated, one_shot_written, one_shot_updated,
     * pr_review_written, step_review_started, step_review_written,
     * stage_started, step_started, compacted or interrupted.
     */
    "type": string;
    "preTokens": number;

    /**
     * Stage belongs to stage_started alone, Step to the markers of a step
     * (step_started, step_review_started), Pass to the markers of a review
     * (pr_review_written, step_review_written) and Clean to
     * step_review_written alone; Restarted belongs to stage_started and
     * step_started.
     */
    "stage": string;
    "step": number;
    "pass": number;
    "clean": boolean;
    "restarted": boolean;
}

/**
 * Migration is a migration of the data that was refused, with what to resolve.
 */
export interface Migration {
    /**
     * never nil
     */
    "cases": MigrationCase[] | null;
}

/**
 * MigrationCase is one reason the migration was refused.
 */
export interface MigrationCase {
    /**
     * Kind is root_task, no_origin or name_conflict, a string for the same
     * reason as State.Theme.
     */
    "kind": string;

    /**
     * no_origin: the path of the clone; name_conflict: owner/name
     */
    "repository": string;

    /**
     * no_origin: why the clone was refused
     */
    "detail": string;

    /**
     * never nil
     */
    "tasks": MigrationTask[] | null;
}

/**
 * MigrationTask is one task a refused migration is about.
 */
export interface MigrationTask {
    "name": string;
    "workspace": string;

    /**
     * the clone; "" for a task at the root of its workspace
     */
    "path": string;
}

/**
 * PRBlock is why the pull request stage of a task cannot go on.
 */
export interface PRBlock {
    /**
     * Reason is gh_missing, gh_unauthenticated, gh_failed, git_failed or
     * no_worktree, a string for the same reason as State.Theme.
     */
    "reason": string;

    /**
     * what gh or git said, verbatim
     */
    "detail": string;
}

/**
 * PRDraft is the description of a pull request the agent wrote and the user
 * edits.
 */
export interface PRDraft {
    "title": string;
    "body": string;

    /**
     * name inside the pr folder, for ReadArtifact
     */
    "file": string;
}

/**
 * PRPreview is a pull request the app leaves on GitHub when the task goes.
 */
export interface PRPreview {
    "number": number;
    "url": string;

    /**
     * State is open, merged or closed; "" when unknown.
     */
    "state": string;
}

/**
 * PRReport is one pass of the review of a pull request.
 */
export interface PRReport {
    "pass": number;

    /**
     * name inside the pr folder, for ReadArtifact
     */
    "file": string;
    "clean": boolean;
}

/**
 * PermissionEntry is a tool the agent asked to use. Input and Suggestions carry
 * raw JSON as a string, because the bindings generator has no stable type for
 * json.RawMessage; the frontend parses them.
 */
export interface PermissionEntry {
    "requestId": string;
    "toolUseId": string;
    "tool": string;
    "displayName": string;
    "description": string;

    /**
     * JSON object
     */
    "input": string;

    /**
     * JSON array, "" when absent
     */
    "suggestions": string;
    "blockedPath": string;
    "decisionReason": string;
    "suppressAlwaysAllow": boolean;
    "defaultToNo": boolean;

    /**
     * Status is pending, allowed, allowed_session, denied or cancelled.
     */
    "status": string;
    "denyMessage": string;

    /**
     * "" while pending
     */
    "answeredAt": string;
}

/**
 * Place is where in a task a situation is.
 */
export interface Place {
    /**
     * Kind is stage, step, step_review or pr, a string for the same reason as
     * State.Theme.
     */
    "kind": string;

    /**
     * stage only: prd, tech_spec, plan or one_shot
     */
    "stage": string;

    /**
     * step and step_review only
     */
    "step": number;
}

/**
 * PlanProblem is one reason the step files are not a valid plan.
 */
export interface PlanProblem {
    /**
     * "" for the plan as a whole
     */
    "file": string;
    "message": string;
}

/**
 * Prompt is the text a kind of session opens with, as the settings show it.
 */
export interface Prompt {
    /**
     * Stage is prd, tech_spec, plan, one_shot, step_review, commit, pr or
     * pr_review, a string for the same reason as State.Theme.
     */
    "stage": string;
    "text": string;

    /**
     * the user edited it: it no longer follows the default of the app
     */
    "modified": boolean;

    /**
     * Placeholders are the placeholders the default of the prompt uses, in the
     * order the settings list them; never nil.
     */
    "placeholders": string[] | null;
}

/**
 * PullRequest is the PR stage of a task, with its conversation and its state.
 */
export interface PullRequest {
    /**
     * Status is preparing, blocked, drafting, draft_ready, awaiting_reply,
     * opening, reviewing, awaiting_decision, in_review, ready_to_approve,
     * committing, done, merged, pr_closed, closing or closed, a string for the
     * same reason as State.Theme.
     */
    "status": string;

    /**
     * blocked only
     */
    "block": PRBlock | null;
    "worktreePath": string;
    "branch": string;
    "baseBranch": string;

    /**
     * nil until the draft is written
     */
    "draft": PRDraft | null;

    /**
     * never nil
     */
    "reports": PRReport[] | null;

    /**
     * the review states and committing only
     */
    "review": Review | null;

    /**
     * CommitFailed says the last approval of the review ended without a commit.
     */
    "commitFailed": boolean;
    "prNumber": number;
    "prUrl": string;

    /**
     * open, merged or closed; "" when unknown
     */
    "prState": string;

    /**
     * CheckedAt is when gh last reported the pull request; "" before that.
     */
    "checkedAt": string;

    /**
     * PRBase is the branch the pull request merges into; "" until read.
     */
    "prBase": string;

    /**
     * CheckError is what the last automatic reading said when it failed; ""
     * otherwise.
     */
    "checkError": string;

    /**
     * the user may close the task now
     */
    "canClose": boolean;

    /**
     * CloneMissing says the closing waits for the clone of the repository.
     */
    "cloneMissing": boolean;

    /**
     * closed only
     */
    "close": CloseResult | null;

    /**
     * "" when the stage has no conversation
     */
    "sessionStage": string;

    /**
     * SessionStatus is working, waiting, needs_permission, needs_answer, paused
     * or error.
     */
    "sessionStatus": string;

    /**
     * SessionModel and SessionEffort are what the session of the stage runs
     * with from its next message on; "" without a session.
     */
    "sessionModel": string;
    "sessionEffort": string;
    "turnRunning": boolean;
    "processRunning": boolean;
    "retryAttempt": number;
    "contextPercent": number;
    "pendingCount": number;
    "lastError": string;
}

/**
 * Question is one of the questions of an AskUserQuestion call.
 */
export interface Question {
    "question": string;
    "header": string;

    /**
     * never nil
     */
    "options": QuestionOption[] | null;
    "multiSelect": boolean;
}

/**
 * QuestionEntry is a structured question the agent asked.
 */
export interface QuestionEntry {
    "requestId": string;
    "toolUseId": string;

    /**
     * never nil
     */
    "questions": Question[] | null;

    /**
     * question text -> label(s); nil while pending
     */
    "answers": { [_ in string]?: string } | null;

    /**
     * Status is pending, allowed or cancelled.
     */
    "status": string;
}

/**
 * QuestionOption is one answer offered for a question.
 */
export interface QuestionOption {
    "label": string;
    "description": string;
}

/**
 * Repository is a registered repository, with what the app knows about its
 * clone and its tasks.
 */
export interface Repository {
    "id": string;
    "owner": string;
    "name": string;

    /**
     * owner/name
     */
    "fullName": string;
    "path": string;

    /**
     * the clone was not at Path at the last check
     */
    "missing": boolean;
    "activeTasks": number;
    "archivedTasks": number;
}

/**
 * RepositoryCandidate is a clone of a GitHub repository the scan found under
 * the home folder.
 */
export interface RepositoryCandidate {
    "owner": string;
    "name": string;

    /**
     * owner/name
     */
    "fullName": string;
    "path": string;

    /**
     * the repository is registered, at this path or another
     */
    "registered": boolean;
}

/**
 * Review is how far the review of a step has got.
 */
export interface Review {
    /**
     * never nil
     */
    "files": ReviewFile[] | null;
    "staged": number;
    "total": number;
    "percent": number;

    /**
     * what git said when the worktree could not be read
     */
    "error": string;
}

/**
 * ReviewFile is one changed file of the worktree of a step under review.
 */
export interface ReviewFile {
    "path": string;

    /**
     * Kind is added, modified, deleted, renamed or untracked, a string for the
     * same reason as State.Theme.
     */
    "kind": string;

    /**
     * nothing of it is left outside the index
     */
    "staged": boolean;
}

/**
 * Situation is something a task cannot go on without the user for.
 */
export interface Situation {
    "id": string;
    "taskId": string;

    /**
     * Kind is session_error, step_blocked, worktree_unreadable, pr_blocked,
     * plan_invalid, pr_closed, permission, question, reply, ready_to_continue,
     * step_review, step_empty, draft, findings, changes_review or merge, a
     * string for the same reason as State.Theme.
     */
    "kind": string;

    /**
     * Group is error, waiting or closing, from the most urgent, a string for
     * the same reason as State.Theme.
     */
    "group": string;

    /**
     * Form is review, staged or approve for step_review and changes_review,
     * merge or close for merge, and "" for every other kind, a string for the
     * same reason as State.Theme.
     */
    "form": string;

    /**
     * staged form only
     */
    "percent": number;
    "place": Place;
    "startedAt": string;
}

/**
 * SituationOpen asks the interface for the place a notification leads to.
 */
export interface SituationOpen {
    "taskId": string;
    "place": Place;
}

/**
 * SituationStarted is a situation that just started, and whether the window
 * was in front of the user when it did.
 */
export interface SituationStarted {
    "situation": Situation;
    "focused": boolean;
}

/**
 * StageModel is the model and effort of one stage.
 */
export interface StageModel {
    /**
     * Stage is prd, tech_spec, plan, one_shot, implementation, step_review, pr
     * or pr_review, a string for the same reason as State.Theme.
     */
    "stage": string;

    /**
     * claude-fable-5-1, claude-opus-5 or claude-sonnet-5
     */
    "model": string;

    /**
     * low, medium, high, xhigh or max
     */
    "effort": string;
}

/**
 * State is everything the interface renders, produced by Go and never derived
 * on the frontend.
 */
export interface State {
    /**
     * Migration is set when the data could not be migrated; every other field
     * is then empty.
     */
    "migration": Migration | null;

    /**
     * Repositories are the registered repositories, by owner/name, ignoring
     * case; never nil.
     */
    "repositories": Repository[] | null;

    /**
     * RepositoryFilter is the id of the repository the task list and the history
     * show; "" for all of them.
     */
    "repositoryFilter": string;

    /**
     * Theme is system, light or dark. It stays a string so the generated
     * bindings leave the narrowing to the frontend union types instead of
     * emitting a TypeScript enum.
     */
    "theme": string;
    "systemDark": boolean;

    /**
     * ModelDefaults are the choices a new task starts each stage with, in workflow
     * order; never nil.
     */
    "modelDefaults": StageModel[] | null;

    /**
     * ReviewModeDefault is manual or agent: who reviews the steps of a new
     * task, a string for the same reason as State.Theme.
     */
    "reviewModeDefault": string;

    /**
     * Tasks are the active tasks of every repository, in creation order; never
     * nil.
     */
    "tasks": TaskSummary[] | null;

    /**
     * History are the archived tasks of every repository, newest first; never
     * nil.
     */
    "history": ArchivedTask[] | null;
}

/**
 * Step is one step of the plan of a task.
 */
export interface Step {
    "number": number;

    /**
     * name inside steps/, the artifact is "steps/" + File; one-shot.md for the single step of a One-Shot task
     */
    "file": string;
    "title": string;

    /**
     * Status is not_started, preparing, blocked, implementing, agent_review,
     * addressing_review, awaiting_review, in_review, ready_to_approve,
     * nothing_to_commit, review_failed, committing or done, a string for the
     * same reason as State.Theme.
     */
    "status": string;

    /**
     * Phase is fetching, creating or checking while preparing; "" otherwise.
     */
    "phase": string;

    /**
     * blocked only
     */
    "block": StepBlock | null;

    /**
     * "" until the worktree of the task exists
     */
    "worktreePath": string;

    /**
     * the review states and committing only
     */
    "review": Review | null;

    /**
     * done only
     */
    "commitSha": string;

    /**
     * done only
     */
    "commitSubject": string;

    /**
     * the last approval ended without a commit
     */
    "commitFailed": boolean;

    /**
     * what the step runs with, or will run with
     */
    "model": string;
    "effort": string;

    /**
     * not started, with a choice of its own instead of the one of implementation
     */
    "adjusted": boolean;

    /**
     * not started: its choice can still change
     */
    "modelEditable": boolean;

    /**
     * ReviewMode is manual or agent: who reviews the step, the mode it will
     * start with or the one it is reviewed with, a string for the same reason
     * as State.Theme.
     */
    "reviewMode": string;

    /**
     * not started, with a mode of its own instead of the one of the task
     */
    "reviewModeAdjusted": boolean;

    /**
     * not started: its mode can still change
     */
    "reviewModeEditable": boolean;

    /**
     * ReviewFallback is taken_over, rounds_exhausted or commit_failed: why a
     * step that started under the agent review is reviewed by the user; ""
     * while its mode holds.
     */
    "reviewFallback": string;

    /**
     * agent_review only: the pass under way
     */
    "reviewPass": number;

    /**
     * addressing_review only: the report the implementer addresses
     */
    "reviewRound": number;

    /**
     * agent_review only: the reviewer rests without the report of the pass
     */
    "reportMissing": boolean;

    /**
     * the reports of the agent review, by pass; never nil
     */
    "reports": StepReport[] | null;

    /**
     * nil while the step has no reviewer conversation open
     */
    "reviewer": StepReviewer | null;
}

/**
 * StepBlock is why a step is blocked.
 */
export interface StepBlock {
    /**
     * Reason is dirty_worktree, fetch_failed, no_base_branch, path_exists,
     * branch_exists, git_failed or clone_missing, a string for the same reason
     * as State.Theme.
     */
    "reason": string;

    /**
     * what git said, or the status lines of a dirty worktree
     */
    "detail": string;

    /**
     * dirty worktree only
     */
    "files": number;
}

/**
 * StepReport is one pass of the agent review of a step.
 */
export interface StepReport {
    "pass": number;

    /**
     * name inside the step-reviews folder, for ReadArtifact
     */
    "file": string;
    "clean": boolean;
}

/**
 * StepReviewer is the conversation that reviews a step, with the state of its
 * session. It has the shape the chat takes from a task and a repository.
 */
export interface StepReviewer {
    /**
     * step_review:<n>
     */
    "sessionStage": string;

    /**
     * SessionStatus is working, waiting, needs_permission, needs_answer, paused
     * or error.
     */
    "sessionStatus": string;
    "sessionModel": string;
    "sessionEffort": string;
    "turnRunning": boolean;
    "processRunning": boolean;
    "retryAttempt": number;
    "contextPercent": number;
    "pendingCount": number;
    "lastError": string;
}

/**
 * TaskStageModel is the model and effort of one stage of a task, with what the
 * user can still do about it.
 */
export interface TaskStageModel {
    /**
     * as StageModel.Stage
     */
    "stage": string;
    "model": string;
    "effort": string;

    /**
     * a session of the stage is still to start
     */
    "editable": boolean;

    /**
     * a session of the stage runs now: it changes in its conversation
     */
    "live": boolean;
}

/**
 * TaskSummary is an active task with the state of its session.
 */
export interface TaskSummary {
    "id": string;
    "name": string;
    "repositoryId": string;

    /**
     * owner/name
     */
    "repository": string;

    /**
     * Mode is structured or one_shot, a string for the same reason as
     * State.Theme.
     */
    "mode": string;

    /**
     * Stage is prd, tech_spec, plan, one_shot, implementation or pr, a string
     * for the same reason as State.Theme.
     */
    "stage": string;

    /**
     * Revisiting is a stage reopened by the user, which moves on only when
     * they say so.
     */
    "revisiting": boolean;

    /**
     * ReviewMode is manual or agent: the mode of the task, which the steps
     * without a mode of their own take.
     */
    "reviewMode": string;

    /**
     * a change of the mode still reaches a step
     */
    "reviewModeEditable": boolean;

    /**
     * SessionStatus is working, waiting, needs_permission, needs_answer, paused
     * or error.
     */
    "sessionStatus": string;

    /**
     * SessionModel and SessionEffort are what the session the task screen shows
     * runs with from its next message on; "" without a session.
     */
    "sessionModel": string;
    "sessionEffort": string;
    "turnRunning": boolean;
    "processRunning": boolean;
    "retryAttempt": number;
    "contextPercent": number;
    "pendingCount": number;
    "corrections": number;
    "hasPrd": boolean;
    "hasTechSpec": boolean;
    "hasOneShot": boolean;

    /**
     * never nil
     */
    "steps": Step[] | null;

    /**
     * the step that runs or runs next; 0 when the task has no steps
     */
    "currentStep": number;

    /**
     * nil outside the pull request stage
     */
    "pr": PullRequest | null;

    /**
     * never nil
     */
    "planProblems": PlanProblem[] | null;

    /**
     * what the task waits on the user for, the most urgent first; never nil
     */
    "situations": Situation[] | null;

    /**
     * every stage, in workflow order; never nil
     */
    "models": TaskStageModel[] | null;
    "canContinue": boolean;
    "artifactVersion": number;
    "lastError": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Transcript is the whole conversation of a task.
 */
export interface Transcript {
    "taskId": string;
    "sessionId": string;

    /**
     * Stage is the stage of the session the conversation belongs to.
     */
    "stage": string;

    /**
     * never nil
     */
    "entries": Entry[] | null;

    /**
     * never nil
     */
    "pending": Entry[] | null;
}

/**
 * TranscriptEvent is one change to the conversation of a task.
 */
export interface TranscriptEvent {
    "taskId": string;
    "stage": string;

    /**
     * Kind is entry, text, remove or reset.
     */
    "kind": string;
    "entry": Entry | null;
    "entryId": string;
    "text": string;
}

/**
 * UserEntry is a message sent to the agent: one the user wrote, or one the app
 * sent on their behalf.
 */
export interface UserEntry {
    "text": string;
    "pending": boolean;
    "prompt": boolean;
    "app": boolean;
}

/**
 * WorktreePreview is the worktree the deletion of a task would remove, and
 * whether it holds work.
 */
export interface WorktreePreview {
    "path": string;
    "dirty": boolean;

    /**
     * changed files; dirty only
     */
    "files": number;

    /**
     * what git said when the worktree could not be read
     */
    "error": string;
}
