// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RepositoryService is the repository API the frontend calls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * AddRepository asks for the folder of a clone and registers it. Cancelling
 * changes nothing and is not an error; a folder the app refuses comes back as
 * the sentence the user reads.
 */
export function AddRepository(): $CancellablePromise<void> {
    return $Call.ByID(1327201862);
}

/**
 * ChangeRepositoryPath asks for the new folder of the clone of a repository.
 */
export function ChangeRepositoryPath(id: string): $CancellablePromise<void> {
    return $Call.ByID(2545565548, id);
}

/**
 * RemoveRepository removes a repository that has no task.
 */
export function RemoveRepository(id: string): $CancellablePromise<void> {
    return $Call.ByID(605300867, id);
}

/**
 * SetRepositoryFilter chooses the repository the task list and the history
 * show; "" shows them all.
 */
export function SetRepositoryFilter(id: string): $CancellablePromise<void> {
    return $Call.ByID(180387811, id);
}
