// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReviewService is the pull request and review API the frontend calls. The
 * conversation of a review goes through TaskService, like the one of a task:
 * the id of the review is the id of the item behind it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyReview asks the agent to fix the findings the user approved, in the
 * worktree of the review.
 */
export function ApplyReview(id: string): $CancellablePromise<void> {
    return $Call.ByID(2876599473, id);
}

/**
 * ApproveRestOfFindings approves every finding of a pass that has no decision.
 */
export function ApproveRestOfFindings(id: string, pass: number): $CancellablePromise<void> {
    return $Call.ByID(3565188877, id, pass);
}

/**
 * ApproveReview approves the changes the agent made and asks it to commit them
 * and push them to the pull request.
 */
export function ApproveReview(id: string): $CancellablePromise<void> {
    return $Call.ByID(821139084, id);
}

/**
 * DecideFinding records what the user decided about one finding: "", approved
 * or discarded.
 */
export function DecideFinding(id: string, pass: number, $number: number, decision: string): $CancellablePromise<void> {
    return $Call.ByID(676270192, id, pass, $number, decision);
}

/**
 * DeleteReview removes a review for good, active or archived, and answers with
 * what git could not remove.
 */
export function DeleteReview(id: string): $CancellablePromise<$models.DeleteResult> {
    return $Call.ByID(355239924, id);
}

/**
 * OpenFindingInEditor opens the line a finding points at, in the window of the
 * worktree of the review. A finding about the pull request as a whole points at
 * no line and cannot be opened.
 */
export function OpenFindingInEditor(id: string, pass: number, $number: number): $CancellablePromise<void> {
    return $Call.ByID(24630302, id, pass, $number);
}

/**
 * OpenReviewInEditor opens the worktree of a review in the user's editor.
 */
export function OpenReviewInEditor(id: string): $CancellablePromise<void> {
    return $Call.ByID(3694769557, id);
}

/**
 * PublishReview sends the findings the user approved to GitHub as one review,
 * with the verdict they chose: approve, request_changes or comment. The
 * summary of the pass goes in the body only with withSummary.
 */
export function PublishReview(id: string, verdict: string, withSummary: boolean): $CancellablePromise<void> {
    return $Call.ByID(2987531066, id, verdict, withSummary);
}

/**
 * ReadReviewArtifact returns the content of an artifact of a review by file
 * name: its context document or the report of one pass.
 */
export function ReadReviewArtifact(id: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(2360141537, id, name);
}

/**
 * RefreshPR reads the pull request of a review now, out of the minute, and
 * answers once the reading is over.
 */
export function RefreshPR(id: string): $CancellablePromise<void> {
    return $Call.ByID(2564923056, id);
}

/**
 * RefreshPullRequests reads the open pull requests of every registered
 * repository again. The reading runs in the background and reaches the
 * interface with the state.
 */
export function RefreshPullRequests(): $CancellablePromise<void> {
    return $Call.ByID(607206883);
}

/**
 * ReviewAgain asks the agent for another pass over the pull request as it is
 * now.
 */
export function ReviewAgain(id: string, instructions: string): $CancellablePromise<void> {
    return $Call.ByID(1524845153, id, instructions);
}

/**
 * SetFindingText records the text of a finding as the user left it, which is
 * what a published comment says.
 */
export function SetFindingText(id: string, pass: number, $number: number, text: string): $CancellablePromise<void> {
    return $Call.ByID(216640681, id, pass, $number, text);
}

/**
 * SetReviewFilters chooses what the Reviews view shows.
 */
export function SetReviewFilters(f: $models.ReviewFilters): $CancellablePromise<void> {
    return $Call.ByID(2689530260, f);
}

/**
 * SetReviewSummary records the summary of a pass as the user left it, which is
 * what the body of a published review opens with.
 */
export function SetReviewSummary(id: string, pass: number, text: string): $CancellablePromise<void> {
    return $Call.ByID(1034859019, id, pass, text);
}

/**
 * StartReview reviews a pull request: it creates the review, its worktree and
 * its conversation, and answers with the id of the review.
 */
export function StartReview(req: $models.StartReviewRequest): $CancellablePromise<string> {
    return $Call.ByID(2997269421, req);
}
