// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the settings API the frontend calls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * SetTheme stores the theme preference: system, light or dark.
 */
export function SetTheme(preference: string): $CancellablePromise<void> {
    return $Call.ByID(3310684687, preference);
}
