// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the settings API the frontend calls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckMachine checks the machine again, or waits for the check that runs,
 * and returns where the check stands after it; the state carries the same
 * with state:changed.
 */
export function CheckMachine(): $CancellablePromise<$models.Machine> {
    return $Call.ByID(3164437063);
}

/**
 * GetPrompt reads a prompt as the settings show it.
 */
export function GetPrompt(stage: string): $CancellablePromise<$models.Prompt> {
    return $Call.ByID(769625320, stage);
}

/**
 * ListPrompts says which prompts the user edited and when, without their text.
 */
export function ListPrompts(): $CancellablePromise<$models.PromptListing[] | null> {
    return $Call.ByID(1474603361);
}

/**
 * RestorePrompt throws the edit of a prompt away, so that it follows the
 * default of the app again.
 */
export function RestorePrompt(stage: string): $CancellablePromise<$models.Prompt> {
    return $Call.ByID(3333511018, stage);
}

/**
 * SavePrompt stores the text of a prompt. The text of the default is no edit:
 * the prompt follows the default again.
 */
export function SavePrompt(stage: string, text: string): $CancellablePromise<$models.Prompt> {
    return $Call.ByID(1716218985, stage, text);
}

/**
 * SetModelDefault stores the model and effort new tasks start a stage with.
 */
export function SetModelDefault(stage: string, model: string, effort: string): $CancellablePromise<void> {
    return $Call.ByID(606692884, stage, model, effort);
}

/**
 * SetReviewModeDefault stores who reviews the steps of the tasks created from
 * now on: manual or agent.
 */
export function SetReviewModeDefault(mode: string): $CancellablePromise<void> {
    return $Call.ByID(2645953726, mode);
}

/**
 * SetTheme stores the theme preference: system, light or dark.
 */
export function SetTheme(preference: string): $CancellablePromise<void> {
    return $Call.ByID(3310684687, preference);
}
