// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StartupService tells the frontend where the startup stands and starts it
 * again after a failure. It answers before the app is ready: it is the one
 * service that never waits.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetStartup returns where the startup stands. It is how the frontend gets its
 * first one; every later one arrives with EventStartupChanged.
 */
export function GetStartup(): $CancellablePromise<$models.Startup> {
    return $Call.ByID(306219459);
}

/**
 * TryAgain runs the startup again from its first step; it does nothing unless
 * the startup failed.
 */
export function TryAgain(): $CancellablePromise<void> {
    return $Call.ByID(3631836577);
}
