// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StateService hands the frontend the state it renders.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetState returns the current snapshot. It is how the frontend gets its first
 * state; every later one arrives with EventStateChanged.
 */
export function GetState(): $CancellablePromise<$models.State> {
    return $Call.ByID(2031471303);
}
