// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TaskService is the task, session and flow API the frontend calls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnswerPermission answers the pending permission request of a task. The
 * decision is allow, allow_session or deny; message is the reason a denial
 * gives the agent.
 */
export function AnswerPermission(taskID: string, stage: string, requestID: string, decision: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3120946951, taskID, stage, requestID, decision, message);
}

/**
 * AnswerQuestion answers the pending structured question of a task, mapping
 * each question text to the chosen label.
 */
export function AnswerQuestion(taskID: string, stage: string, requestID: string, answers: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(1425414620, taskID, stage, requestID, answers);
}

/**
 * ApprovePR approves the review of the changes a pass of the pull request
 * review produced and asks the agent to commit and push them.
 */
export function ApprovePR(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(1918022829, taskID);
}

/**
 * ApproveStep approves the review of the current step of a task and asks the
 * agent to commit what is staged.
 */
export function ApproveStep(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3269304029, taskID);
}

/**
 * BackToStage reopens a finished stage of a task, throwing away what came
 * after it. The stage is prd, tech_spec or one_shot.
 */
export function BackToStage(taskID: string, stage: string): $CancellablePromise<void> {
    return $Call.ByID(398771202, taskID, stage);
}

/**
 * CleanAndStartStep throws away every change of the worktree of a step blocked
 * by a dirty one and prepares it again.
 */
export function CleanAndStartStep(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(4154159802, taskID);
}

/**
 * CloseTask takes down the worktree and the branch of a task whose pull request
 * was merged and updates the base branch of its clone. It returns as soon as
 * the work is scheduled; what git does arrives as state.
 */
export function CloseTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3543739215, taskID);
}

/**
 * ContinueStage moves a task that is revisiting a stage on to the next one.
 */
export function ContinueStage(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(4194253291, taskID);
}

/**
 * CreateTask creates a task and starts its first stage with the stage prompt.
 * A session that fails to start undoes the task, so a half-created one is
 * never left behind.
 */
export function CreateTask(req: $models.CreateTaskRequest): $CancellablePromise<string> {
    return $Call.ByID(624645295, req);
}

/**
 * DeleteTask stops the session of a task, removes its worktree and its branch,
 * and removes it with its artifacts. What git could not remove comes back for
 * the user to clean up: it never keeps the task.
 */
export function DeleteTask(taskID: string): $CancellablePromise<$models.DeleteResult> {
    return $Call.ByID(797789264, taskID);
}

/**
 * DiscardDraft throws away the draft of a task and prepares the stage again.
 */
export function DiscardDraft(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2351206339, taskID);
}

/**
 * DiscardStage throws away a stage and everything after it, and starts the
 * stage again. The stage is prd, tech_spec, plan or one_shot.
 */
export function DiscardStage(taskID: string, stage: string): $CancellablePromise<void> {
    return $Call.ByID(3069692862, taskID, stage);
}

/**
 * DiscardStep throws away the conversation of the current step and starts it
 * over, optionally cleaning its worktree first.
 */
export function DiscardStep(taskID: string, cleanWorktree: boolean): $CancellablePromise<void> {
    return $Call.ByID(216385730, taskID, cleanWorktree);
}

/**
 * GetTranscript returns the whole conversation of one session of a task, named
 * by its stage. It is how the frontend gets its first one; every later change
 * arrives with EventTranscriptChanged.
 */
export function GetTranscript(taskID: string, stage: string): $CancellablePromise<$models.Transcript> {
    return $Call.ByID(923740112, taskID, stage);
}

/**
 * Interrupt aborts the running turn of a task, leaving the session alive.
 */
export function Interrupt(taskID: string, stage: string): $CancellablePromise<void> {
    return $Call.ByID(1759278057, taskID, stage);
}

/**
 * OpenFileInEditor opens one file of the worktree of a task in the editor, in
 * the window of that worktree.
 */
export function OpenFileInEditor(taskID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1486307698, taskID, path);
}

/**
 * OpenInEditor opens the worktree of a task in the editor.
 */
export function OpenInEditor(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(1075572732, taskID);
}

/**
 * OpenPR writes the draft the user approved and asks the agent to open the
 * pull request of the task from it.
 */
export function OpenPR(taskID: string, title: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(1566738704, taskID, title, body);
}

/**
 * Pause stops the process of a task and holds every message until Resume.
 */
export function Pause(taskID: string, stage: string): $CancellablePromise<void> {
    return $Call.ByID(2312621456, taskID, stage);
}

/**
 * PreviewDelete reads what deleting a task would destroy, which is what the
 * confirmation dialog spells out before the user agrees to it.
 */
export function PreviewDelete(taskID: string): $CancellablePromise<$models.DeletePreview> {
    return $Call.ByID(1203630309, taskID);
}

/**
 * ReadArtifact returns the content of an artifact of a task by file name.
 */
export function ReadArtifact(taskID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3512098012, taskID, name);
}

/**
 * RefreshPR reads the pull request of a task again. It returns as soon as the
 * reading is scheduled; what it finds arrives as state.
 */
export function RefreshPR(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3606863055, taskID);
}

/**
 * RemovePending drops a queued message before it reaches the agent.
 */
export function RemovePending(taskID: string, stage: string, entryID: string): $CancellablePromise<void> {
    return $Call.ByID(1420869509, taskID, stage, entryID);
}

/**
 * Resume lifts a pause and delivers what was queued meanwhile.
 */
export function Resume(taskID: string, stage: string): $CancellablePromise<void> {
    return $Call.ByID(4230167665, taskID, stage);
}

/**
 * Retry clears the last error of a task and starts its process again.
 */
export function Retry(taskID: string, stage: string): $CancellablePromise<void> {
    return $Call.ByID(696681228, taskID, stage);
}

/**
 * RetryPR prepares a blocked pull request stage again.
 */
export function RetryPR(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2206023154, taskID);
}

/**
 * RetryStep prepares a blocked step again, which is what the user asks for
 * after fixing whatever git complained about.
 */
export function RetryStep(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3942932222, taskID);
}

/**
 * ReviewAgain ends the review session of a task and starts a new pass over its
 * pull request.
 */
export function ReviewAgain(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3401154390, taskID);
}

/**
 * ReviewStepMyself takes the review of the current step of a task back from
 * the agent.
 */
export function ReviewStepMyself(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(4291051464, taskID);
}

/**
 * SendMessage queues a message for the agent, delivered right away when the
 * session is free.
 */
export function SendMessage(taskID: string, stage: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(2431074491, taskID, stage, text);
}

/**
 * SetReviewMode changes who reviews the steps of a task that are still to
 * start and have no mode of their own.
 */
export function SetReviewMode(taskID: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(3676650109, taskID, mode);
}

/**
 * SetSessionModel changes the model and effort of a session from its next
 * message on. The stage names the session: prd, tech_spec, plan, one_shot,
 * step:<n>, step_review:<n>, pr or pr_review.
 */
export function SetSessionModel(taskID: string, stage: string, model: string, effort: string): $CancellablePromise<void> {
    return $Call.ByID(2320848335, taskID, stage, model, effort);
}

/**
 * SetStageModel changes the model and effort of a stage of a task, for the
 * sessions of it that are still to start.
 */
export function SetStageModel(taskID: string, stage: string, model: string, effort: string): $CancellablePromise<void> {
    return $Call.ByID(2857821909, taskID, stage, model, effort);
}

/**
 * SetStepModel changes the model and effort of a step that has not started.
 */
export function SetStepModel(taskID: string, step: number, model: string, effort: string): $CancellablePromise<void> {
    return $Call.ByID(3274288345, taskID, step, model, effort);
}

/**
 * SetStepReviewMode changes who reviews a step that has not started.
 */
export function SetStepReviewMode(taskID: string, step: number, mode: string): $CancellablePromise<void> {
    return $Call.ByID(617698371, taskID, step, mode);
}
