// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TaskService is the task, session and flow API the frontend calls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnswerPermission answers the pending permission request of a task. The
 * decision is allow, allow_session or deny; message is the reason a denial
 * gives the agent.
 */
export function AnswerPermission(taskID: string, requestID: string, decision: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3120946951, taskID, requestID, decision, message);
}

/**
 * AnswerQuestion answers the pending structured question of a task, mapping
 * each question text to the chosen label.
 */
export function AnswerQuestion(taskID: string, requestID: string, answers: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(1425414620, taskID, requestID, answers);
}

/**
 * BackToStage reopens a finished stage of a task, throwing away what came
 * after it. The stage is prd or tech_spec.
 */
export function BackToStage(taskID: string, stage: string): $CancellablePromise<void> {
    return $Call.ByID(398771202, taskID, stage);
}

/**
 * CleanAndStartStep throws away every change of the worktree of a step blocked
 * by a dirty one and prepares it again.
 */
export function CleanAndStartStep(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(4154159802, taskID);
}

/**
 * ContinueStage moves a task that is revisiting a stage on to the next one.
 */
export function ContinueStage(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(4194253291, taskID);
}

/**
 * CreateTask creates a task and starts its first stage with the stage prompt.
 * A session that fails to start undoes the task, so a half-created one is
 * never left behind.
 */
export function CreateTask(req: $models.CreateTaskRequest): $CancellablePromise<string> {
    return $Call.ByID(624645295, req);
}

/**
 * DeleteTask stops the session of a task, removes its worktrees and branches,
 * and removes it with its artifacts. A worktree git cannot remove keeps the
 * task, and the reason reaches the user.
 */
export function DeleteTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(797789264, taskID);
}

/**
 * DiscardStage throws away a stage and everything after it, and starts the
 * stage again. The stage is prd, tech_spec or plan.
 */
export function DiscardStage(taskID: string, stage: string): $CancellablePromise<void> {
    return $Call.ByID(3069692862, taskID, stage);
}

/**
 * DiscardStep throws away the conversation of the current step and starts it
 * over, optionally cleaning its worktree first.
 */
export function DiscardStep(taskID: string, cleanWorktree: boolean): $CancellablePromise<void> {
    return $Call.ByID(216385730, taskID, cleanWorktree);
}

/**
 * GetTranscript returns the whole conversation of a task. It is how the
 * frontend gets its first one; every later change arrives with
 * EventTranscriptChanged.
 */
export function GetTranscript(taskID: string): $CancellablePromise<$models.Transcript> {
    return $Call.ByID(923740112, taskID);
}

/**
 * Interrupt aborts the running turn of a task, leaving the session alive.
 */
export function Interrupt(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(1759278057, taskID);
}

/**
 * OpenInEditor opens the worktree of the current step of a task in the editor.
 */
export function OpenInEditor(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(1075572732, taskID);
}

/**
 * Pause stops the process of a task and holds every message until Resume.
 */
export function Pause(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2312621456, taskID);
}

/**
 * ReadArtifact returns the content of an artifact of a task by file name.
 */
export function ReadArtifact(taskID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3512098012, taskID, name);
}

/**
 * RemovePending drops a queued message before it reaches the agent.
 */
export function RemovePending(taskID: string, entryID: string): $CancellablePromise<void> {
    return $Call.ByID(1420869509, taskID, entryID);
}

/**
 * Resume lifts a pause and delivers what was queued meanwhile.
 */
export function Resume(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(4230167665, taskID);
}

/**
 * Retry clears the last error of a task and starts its process again.
 */
export function Retry(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(696681228, taskID);
}

/**
 * RetryStep prepares a blocked step again, which is what the user asks for
 * after fixing whatever git complained about.
 */
export function RetryStep(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3942932222, taskID);
}

/**
 * SendMessage queues a message for the agent, delivered right away when the
 * session is free.
 */
export function SendMessage(taskID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(2431074491, taskID, text);
}
