// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService is the workspace API the frontend calls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DismissNotice clears the notice the interface is showing.
 */
export function DismissNotice(): $CancellablePromise<void> {
    return $Call.ByID(2962589610);
}

/**
 * GetState returns the current snapshot. It is how the frontend gets its first
 * state; every later one arrives with EventStateChanged.
 */
export function GetState(): $CancellablePromise<$models.State> {
    return $Call.ByID(2350426031);
}

/**
 * OpenFolderDialog asks the user for a folder and opens it. Cancelling changes
 * nothing and is not an error.
 */
export function OpenFolderDialog(): $CancellablePromise<void> {
    return $Call.ByID(1530113326);
}

/**
 * OpenPath opens an absolute path as the workspace. A path that no longer
 * qualifies turns into a notice rather than an error, which is what the recent
 * list needs when a folder is gone.
 */
export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(478390629, path);
}

/**
 * RemoveRecent drops a path from the recent workspaces.
 */
export function RemoveRecent(path: string): $CancellablePromise<void> {
    return $Call.ByID(971993057, path);
}
